#!/bin/sh /etc/rc.common
START=98 
STOP=98

start()  {
    echo "tuyaapp Start" >> /dev/ttyS0
	mount -t vfat /dev/mmcblk0 /mnt/
    amixer sset "Headphone" 90
    amixer sset "Speaker" 90
    amixer sset "Left Output Mixer PCM" on
    amixer sset "Right Output Mixer PCM" on
    amixer sset "Left Input Mixer Boost" on
    amixer sset "Right Input Mixer Boost" on
    amixer sset "ALC Function" "Stereo"
}

stop() {
	echo "tuyaapp stop" >> /dev/ttyS0
	#killall user_iot
}

restart() {
	stop
	sleep 1
	start
}

